### ISSUE TITLE
aws-node-alexa-skill example response causing error in Service Simulator Tool

### ISSUE THREAD

**Issue by jloveland** [serverless/examples#100]
https://github.com/serverless/examples/tree/master/aws-node-alexa-skill
I get the following when invoking the skill using the Service Simulator Tool
**Error: There was a failure invoking your skill with text input, please try again.**

The solution was to send the setEndSession attribute in the response because it is a required field when using the Service Simulator Tool to test the skill. I set `shouldEndSession: false` in the response and it resolved the issue

reference:
https://forums.developer.amazon.com/questions/57631/error-there-was-a-failure-invoking-your-skill-with-3.html

**Comment by DavidWells** [comment]
Thanks for the report @jloveland do you want submit a PR for this? =)

Do mean https://github.com/serverless/examples/blob/master/aws-node-alexa-skill/handler.js#L15 needs `"shouldEndSession": true` right?

![image](https://cloud.githubusercontent.com/assets/532272/23325965/6d8768fc-faae-11e6-8fb8-afdda5527cee.png)

**Comment by jloveland** [comment]
yes sir @DavidWells

I added PR #101 to fix this issue
