### ISSUE TITLE
aws-node-rest-api-with-dynamodb-and-offline doesn't send data back on create

### ISSUE THREAD

**Issue by remicastaing** [serverless/examples#111]
On create, the CRUD API doesn't send any response back. Obviously, it should (`create.js`):
```
    // create a response
    const response = {
      statusCode: 200,
      body: JSON.stringify(result.Item),
    };
    callback(null, response);
```

Could it be a restriction on `POST`with `serverless-offline`?

**Comment by Rebsos** [comment]
I just had the same problem. To get some data back, define the ReturnValues property in your params object.

Example:
```
  const params = {
    TableName: 'my-table',
    Item: {
      id: 3
    },
    ReturnValues: 'ALL_OLD'           //<===
  };

  dynamoDb.put(params, function(error, result) {
    const response = {
      statusCode: 200,
      body: JSON.stringify(result),
    };
    callback(null, response);
  });
```

**Comment by remicastaing** [comment]
@Rebsos, but your are only getting something back when you overwrite a document:

> ALL_OLD - If PutItem overwrote an attribute name-value pair, then the content of the old item is returned.

**Comment by Rebsos** [comment]
You're right @remicastaing. But at least you get something back.

`NONE - If ReturnValues is not specified, or if its value is NONE, then nothing is returned. (This setting is the default for ReturnValues.)`

Maybe `result.Item` is wrong in the example, it should be `params.Item`. If no error occurs, we could expect that the item was created.

**Comment by remicastaing** [comment]
I also went to the same solution, @Rebsos.

It's just annoying if you want to chain some Promise.

**Comment by remicastaing** [comment]
Ok, I found It: dynamodb.put doesn't return any result.

**Comment by christophgysin** [comment]
I sent a PR that will return the item on success.
