### ISSUE TITLE
aws-node-rest-api-with-dynamodb doesn't allow to add Body Mapping Templates 

### ISSUE THREAD

**Issue by RickyGeek** [serverless/examples#118]
Why there isn't the possibility to add a Body Mapping Templates to the resource?

![screen shot 2017-03-25 at 1 29 35 am](https://cloud.githubusercontent.com/assets/3509884/24317734/c1c321c4-10fa-11e7-9153-3cbb2672221a.png)

**Comment by christophgysin** [comment]
If you uncheck "Use Lambda Proxy integration", you should be able to add Body Mapping Templates.

**Comment by RickyGeek** [comment]
@christophgysin btw if I uncheck it I get a 500 error calling the resource

**Comment by christophgysin** [comment]
Check if the lambda gets triggered, and check the logs to see why it failed.
