### ISSUE TITLE
aws-node-auth0-custom-authorizers-api example gives me CORS error

### ISSUE THREAD

**Issue by saschajullmann** [serverless/examples#120]
Hi,

I was just trying out the above mentioned example and it didn't work for me. I did everything exactly like the README stated. The error occurs when I'm trying to invoke the API calls (so logging into auth0 and obtaining a token works). Whether I call the public endpoint or the private endpoint it gives me the typical "No 'Access-Control-Allow-Origin' header is present on the requested resource". Even though cors is set to '*' (as you can see in the serverless.yml). Even when I specifically enter my sites URL (instead of '*') it won't work. When I test the API in the API Gateway console the Access-Control-Allow-Origin is present. 

Any ideas?

**Comment by christophgysin** [comment]
> Even though cors is set to '' (as you can see in the serverless.yml).

Your comment makes it sound like you have an empty `cors` definition in serverless.yml. Are you using the example from current master? See:
https://github.com/serverless/examples/blob/master/aws-node-auth0-custom-authorizers-api/serverless.yml#L27-L35

**Comment by saschajullmann** [comment]
I just see I had a typo in my first comment. What I was saying was: "Even though CORS is set to allow '*'. So yeah, I did use the example from the current master (I cloned the repo). I still get the error. And when I manually enable cors in the API Gateway console it has no effect. Maybe I should remove everything and try again.

**Comment by saschajullmann** [comment]
Nevermind. I mixed up the API URL -,-. Sorry!

**Comment by LightChang** [comment]
I also got CORS error. I checked "Allowed Origins (CORS)" settings in Auth0, "frontend/app.js", and "secrets.json" several time. Even I remove everything and try again. I still got message.
Please help me.
![2018-04-15 16 26 10](https://user-images.githubusercontent.com/1871386/38776501-46c4b5fe-40ca-11e8-8064-eeae9f969a98.png)
