### ISSUE TITLE
UUIDs *and* timestamps?

### ISSUE THREAD

**Issue by gritzko** [serverless/examples#149]
```
{"text":"Learn Serverless","id":"ee6490d0-aa81-11e6-9ede-afdfa051af86","createdAt":1479138570824,"checked":false,"updatedAt":1479138570824}%
```
I used to think, UUID is a timestamp plus process id (v1)
Are these UUIDs random (v4) ?

**Comment by christophgysin** [comment]
The purpose of the UUID is to have a unique key for the entry. The purpose of the timestamps are to tell you when an entry was created/updated.

**Comment by gritzko** [comment]
v1 UUIDs kind of do both.
https://www.ietf.org/rfc/rfc4122.txt

**Comment by gritzko** [comment]
also https://www.npmjs.com/package/uuid#uuidv1-options--buffer--offset-

**Comment by christophgysin** [comment]
What exactly is the issue here? You are free to use UUIDv4 instead.

**Comment by gritzko** [comment]
Sorry, I was just reading examples.
Saw something I considered bizarre.
