### ISSUE TITLE
Sending a schedule email for the weather in a specific location once every day

### ISSUE THREAD

**Issue by nikgraf** [serverless/examples#15]
Let us know if you interested to work on this. I comment here if one of the core-team is starting to work on it.

**Comment by yubozhao** [comment]
@nikgraf I will do this one as well

**Comment by nikgraf** [comment]
awesome @yubozhao, you rock 🎸 😄

**Comment by tmilewski** [comment]
Jumped ahead and wrote this one out. ;-)

**Comment by yubozhao** [comment]
Noooooooooo.  J/k. Good job @tmilewski.  Thank you for covering this one for me.
