### ISSUE TITLE
aws-node-rest-api-with-dynamodb -- server error

### ISSUE THREAD

**Issue by mabrennan** [serverless/examples#152]
I worked through this particular example.  The stack completes and the DynamoDB table is created just fine.  When I try to create a ToDo item, the response is "message", "internalServererror".  Not sure what a did wrong.

**Comment by waltermvp** [comment]
Make sure to run 'npm install'

**Comment by mabrennan** [comment]
I ran npm install to copy locally, and deployment was successful.  It's when I run:

curl -X POST https://<myEndPointInfo>.execute-api.us-east-1.amazonaws.com/dev/todos --data '{"text": "Learn Serverless" }'

that I get the response, {"message": "Internal server error"}

**Comment by mabrennan** [comment]
Also, I did make sure to grab the actual POST url, which was displayed after running serverless deploy.

**Comment by waltermvp** [comment]
did you get anything from the logs https://serverless.com/framework/docs/providers/aws/cli-reference/logs/

**Comment by mabrennan** [comment]
running serverless logs -f create returns the following:

START RequestId: 93ba8153-3b08-11e7-ae9c-8b39059efa8e Version: $LATEST
Unable to import module 'todos/create': Error
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/task/todos/create.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
END RequestId: 93ba8153-3b08-11e7-ae9c-8b39059efa8e
REPORT RequestId: 93ba8153-3b08-11e7-ae9c-8b39059efa8e	Duration: 7.65 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 19 MB

**Comment by mabrennan** [comment]
Nevermind.  Issue was on my end.  One of two issues:  I realized the system time was off by 10 minutes, which I corrected.  Also, as seen in another posted, after running npm install to pull this code locally, I also then ran npm install --save uuid.  After running the deployment and trying again, the create function worked.

**Comment by waltermvp** [comment]
Seems to me you were missing UUID by not running `npm install`. Great it's working now
