### ISSUE TITLE
Uploading content to an S3 bucket

### ISSUE THREAD

**Issue by nikgraf** [serverless/examples#16]

**Comment by yubozhao** [comment]
I might take a stab at it.

**Comment by nikgraf** [comment]
@yubozhao awesome ✨ then we focus on other examples for now :)

**Comment by yubozhao** [comment]
https://github.com/serverless/examples/pull/22

**Comment by tmilewski** [comment]
@nikgraf I think that this can be closed per the merge of #22.

**Comment by christophgysin** [comment]
@nikgraf Could you close this?

**Comment by nikgraf** [comment]
Sorry I actually meant a different use-case with this issue. A simple Website that directly uploads a file directly to S3 via an ajax request and then the Lambda is reacting reacting to an S3 creation event.

**Comment by christophgysin** [comment]
I see. I can look into this tomorrow.

**Comment by nikgraf** [comment]
@christophgysin I saw your PR. Looks good! Would you also be interested in doing a PR where the file is uploaded from a form in a provided index.html?

**Comment by christophgysin** [comment]
@nikgraf Sure, I can look into that.

**Comment by christophgysin** [comment]
I moved the change to a new example aws-node-upload-to-s3-and-postprocess, which also includes a HTML form based upload.

**Comment by christophgysin** [comment]
@nikgraf Let me know if there is anything I could still improve to get this merged.

**Comment by PalashBansal96** [comment]
aws-node-upload-to-s3-and-postprocess doesn't seem to work now with AWS S3, it requires AWS4-HMAC-SHA256 signatures in most regions now.
