### ISSUE TITLE
Can I use serverless to define an initializer of a DynamoDB table?

### ISSUE THREAD

**Issue by syang** [serverless/examples#167]
I'd like to write several initial items as the initial values in a table, could I automate this process using Serverless framework?

My idea is as the following:

1.  define DynamoDB as what normal serverless.yml does;
2. define handler.js as what normal lambda function definitions do;
3. define an init_handler.js as call that handler once (and only once) during `serverless deploy` command

I don't know if and how I may hack serverless to achieve this.

**Comment by ecoruh** [comment]
This is exactly what we need too. It sounds simple but a very important requirement. The rationale in our case is, we would like to be able to create stock/fake entities as part of our CI/CD at the UAT stage, through which we trigger user acceptance testing with internal stakeholders. Fake entities are needed for agile/strategic reasons as that way we can deliver APIs efficiently in parallel without necessarily completing features. However in our CD pipeline we don't have permissions to create stock entities at the UAT stage, but we can create them via build scripts. Addressing this would have eliminated for us to write and maintain seperate CLI scripts in the post deployment step. Best of all they can be unit tested as part of functional unit tests. Great idea.

**Comment by christophgysin** [comment]
Couldn't you just define init_handler.js as it's own lambda, and invoke it (with sls invoke) after sls deploy?

**Comment by ecoruh** [comment]
I didn't know about `sls invoke`. Great tip @christophgysin thanks!

**Comment by alexdebrie** [comment]
@ecoruh @syang There's a [Serverless DynamoDB local plugin](https://github.com/99xt/serverless-dynamodb-local) that has a `seed` command to load a local DynamoDB table with data from a `.json` file. You could repurpose that to use the `seed` command for an _actual_ DynamoDB table.
