### ISSUE TITLE
Getting an error when attempting to deploy an Alexa skill

### ISSUE THREAD

**Issue by bsatrom** [serverless/examples#241]
I'm attempting to deploy an Alexa skill and am seeing the following deployment error:

![screenshot 2018-01-25 13 53 17](https://user-images.githubusercontent.com/108356/35409191-1dce6b04-01d7-11e8-8e62-94139a057986.png)

```bash
ServerlessError: User: arn:aws:iam::831933616546:user/alexa-skills is not authorized to perform: cloudformation:DescribeStacks on resource: arn:aws:cloudformation:us-east-1:831933616546:stack/aws-node-alexa-skill-dev/*
```

I'm seeing this with my own code as well as the [aws-node-alexa-skill](https://github.com/serverless/examples/tree/master/aws-node-alexa-skill) example, unchanged.

- Node version is 6.10.0
- Serverless version is 1.25.0

**Comment by darrenhgc** [comment]
This seems to be a permissions issue with you alexa-skills user.

**Comment by bsatrom** [comment]
Thanks for the input, that was it, indeed.
