### ISSUE TITLE
aws-node-rest-api-with-dynamodb not up-to-date

### ISSUE THREAD

**Issue by rudyhadoux** [serverless/examples#255]
In examples/aws-node-rest-api-with-dynamodb/serverless.yml there is no stage variable in the provider.

And this page is out of date :
https://aws.amazon.com/fr/blogs/aws/auto-scale-dynamodb-with-dynamic-dynamodb/

DynamoDB is configurable for auto-scaling.

**Comment by darrenhgc** [comment]
`dev` is the [default](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/) stage when none is provided.
