### ISSUE TITLE
aws-node-auth0-custom-authorizers-api example gives me CORS error

### ISSUE THREAD

**Issue by LightChang** [serverless/examples#257]
I got CORS error. I checked "Allowed Origins (CORS)" settings in Auth0, "frontend/app.js", and "secrets.json" several time. Even I remove everything and try again. I still got message.
Please help me.
![2018-04-15 16 26 10](https://user-images.githubusercontent.com/1871386/38792966-e54d5854-4181-11e8-9b0a-6a2e4cc3be6b.png)

**Comment by lis186** [comment]
The https://github.com/serverless/examples/pull/251 pull request will fix CORS error, and other problems you will face.

**Comment by torntrousers** [comment]
+1 on https://github.com/serverless/examples/pull/251
