### ISSUE TITLE
You are running an outdated version of the Serverless Framework. Error reference WSM6MQXX2G02

### ISSUE THREAD

**Issue by elouizbadr** [serverless/examples#301]
Dear collaborators,

I'm facing this issue when I try to deploy using serverless framework.
I tried to update the serverless package but that didn't help since it's the latest at this moment.
Exacte error message -----------------------------------------------------
```
{"errorMessage":"You are running an outdated version of the Serverless Framework. Please update and try again. - Please contact support and provide this identifier to reference this issue - WSM6MQXX202"}
````

My Environment Information ---------------------------------------------
- OS:                     win32
- Node Version:           8.9.1
- Serverless Version:     1.31.0

Thanks,
ELOUIZ BADR

**Comment by eahefnawy** [comment]
1.32.0 is the latest version. Also, if you logout, you won't face this issue.

**Comment by elouizbadr** [comment]
@eahefnawy Thanks for your feedback. Actually the problem happened to me before version 1.32.0 was released. It is a BUG that happened to many others, you can check this issue I created one the serverless code project:
https://github.com/serverless/serverless/issues/5307

Thanks.

**Comment by elouizbadr** [comment]
Related to https://github.com/serverless/serverless/issues/5307
