### ISSUE TITLE
Data ingestion examples

### ISSUE THREAD

**Issue by mthenw** [serverless/examples#37]
```
                                                                               
     ┌──────────┐    ┌──────────┐   ┌───────────┐   ┌──────────┐   ┌──────────┐
     │          │    │  Lambda  │   │           │   │  Lambda  │   │          │
     │   APIG   │───▶│(validate)│──▶│  Kinesis  │──▶│(process &│──▶│ DynamoDB │
     │          │    │          │   │           │   │  save)   │   │          │
     └──────────┘    └──────────┘   └───────────┘   └──────────┘   └──────────┘

```

Real world use case in analytics systems. Tracking most visited pages.

It's pretty common pattern to expose some endpoint and push incoming messages to Kinesis steam. Second Lambda function takes care of processing and saving to DynamoDB.

DynamoDB table:
- url: string
- count: int

Incoming events:

```
{url: 'http://'}
```

**Comment by pmuens** [comment]
Just dropping this related service here which also implements Kinesis streams to count visits: https://github.com/ServerlessInc/serverlessconf-workshop/blob/master/serverless.yml

**Comment by DavidWells** [comment]
@mthenw did you add this? =)

**Comment by mthenw** [comment]
Nope, but there is one similar https://github.com/serverless/examples/tree/master/aws-node-text-analysis-via-sns-post-processing so I think we can close this issue.
