### ISSUE TITLE
TodosDynamoDbTable - todos already exists.

### ISSUE THREAD

**Issue by JSafaiyeh** [serverless/examples#38]
How does serverless handle DynameDb instances? Running `sls destory` does not remove the DB instance from AWS.

**Comment by DavidWells** [comment]
Run `sls remove` to remove the service

https://serverless.com/framework/docs/providers/aws/cli-reference/remove/

**Comment by JSafaiyeh** [comment]
Whoops, yeah I was running `sls remove`

Tried again and I am getting the same behavior.
![screen shot 2016-12-23 at 2 31 08 pm](https://cloud.githubusercontent.com/assets/8675043/21463334/941bcf08-c91c-11e6-91a1-fe7b66aa073f.png)

**Comment by DavidWells** [comment]
You might need to login to your AWS console and go to cloudformation and manually delete the stack that is causing this issue.

**Comment by nikgraf** [comment]
@JSafaiyeh the tables DeletionPolicy is set to retain in the example. This means even if you run `serverless remove` the Table will not be removed to prevent data loss.

You need to go into the console and remove the table manually. Then you can deploy again. Of course you also can change the table name. Let me know if this worked for you 🙂

**Comment by QuantumInformation** [comment]
Does `sls remove` involve less steps than using the AWS console?
