### ISSUE TITLE
'roleName' failed to satisfy constraint

### ISSUE THREAD

**Issue by olileach** [serverless/examples#405]
Hi,

I just deployed this solution following the instructions but got the following error:

➜  aws-node-serve-dynamic-html-via-http-endpoint serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service aws-node-serve-dynamic-html-via-http-endpoint.zip file to S3 (2.41 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.....
Serverless: Operation failed!
Serverless: View the full error output: ...<url>

  Serverless Error ---------------------------------------

  An error occurred: IamRoleLambdaExecution - 1 validation error detected: Value 'aws-node-serve-dynamic-html-via-http-endpoint-dev-us-east-1-lambdaRole' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError; Request ID: 68e27de3-afd5-4f49-9a9e-00e9ee176868).

**Comment by oliverleach** [comment]
It looks like the role name is longer than 64 characters and therefore fails to create.

aws-node-serve-dynamic-html-via-http-endpoint-dev-us-east-1-lambdaRole

**Comment by JuHwon** [comment]
i think this should be an issue still.
i just updated serverless and deployments are not working anymore because now the roleName is too long. so there is imo a breaking change.

**Comment by oliverleach** [comment]
I’ll raise a PR if I get round to it and change the role name to be shorter.. thanks for the comment @juhwon

**Comment by d3netxer** [comment]
what field in the serverless.yaml gets used to build the roleName?

**Comment by yeukfei02** [comment]
i encounter the same error.

```
An error occurred: IamRoleLambdaExecution - 1 validation error detected: Value 'hacker-news-node-typescript-serverless-v1-ap-southeast-1-lambdaRole' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError; Request ID: 7d2de576-4caf-4234-8f3a-d96042db22b8; Proxy: null).
```
