### ISSUE TITLE
Jwt decode vs verify

### ISSUE THREAD

**Issue by tvb** [serverless/examples#458]
Looking at https://github.com/serverless/examples/blob/ae758f8603b1465fed19a93c4f91e765574f6a49/aws-python-auth0-custom-authorizers-api/lambda_handlers.py#L50 I am wondering why the author opted for `jwt.decode` instead of `jwt.verify`.

As far as I understand `jwt.verify` is saver https://community.auth0.com/t/does-jwt-decode-functionality-verify-the-token-or-only-decode-the-token-if-yes-what-all-does-the-decode-function-do/9509/2

**Comment by fernando-mc** [comment]
@tvb Great question, I think that the implementation differs depending on the library used to work with the payload.

The particular library referenced in that Auth0 community post is a node library that has a separate `decode` and `verify` method. 

In the case of the library used in that example it appears to be PyJWT. After checking the docs myself it appears that library has a different implementation in which `decode` both decodes the claims *and* verifies them.

The difference between the two implementations is a bit counterintuitive in my opinion but I think this is confirmed in [the docs](https://pyjwt.readthedocs.io/en/latest/usage.html#reading-the-claimset-without-validation) for PyJWT.

You'll also see similar implementations in other Python libraries like [`jose`](https://python-jose.readthedocs.io/en/latest/jwt/api.html#jose.jwt.decode).
 which says that the `decode` method - "Verifies a JWT string’s signature and validates reserved claims."
