### ISSUE TITLE
Relax linting rules

### ISSUE THREAD

**Issue by DavidWells** [serverless/examples#47]
Console.logs are a part of lamdba functions. I vote we turn off this linting rule.

https://github.com/serverless/examples/blob/master/aws-node-github-webhook-listener/handler.js#L41 Code gets noisy with all the disable flags for the linter

Also, we should disable the "no var" linting rule because "let" isn't currently supported

**Comment by nikgraf** [comment]
@DavidWells sounds good @ relaxing the linting rules. Wanna create a PR?

afaik const & let are supported in node 4

```
➜  aws-java-simple-http-endpoint git:(master) nvm use v4.3.2
Now using node v4.3.2 (npm v2.14.12)
➜  aws-java-simple-http-endpoint git:(master) node --version
v4.3.2
➜  aws-java-simple-http-endpoint git:(master) node
> let a = 2;
undefined
> a
2
> 
```
