### ISSUE TITLE
Unable to deploy babel example

### ISSUE THREAD

**Issue by cmoel** [serverless/examples#51]
Hello!

I'm trying to get the babel example working (https://github.com/serverless/examples/tree/master/aws-node-function-compiled-with-babel) but I've run into an error and can't figure out how to move forward. First, I was running into an error because `node_modules/.bin/babel` didn't exist (installing `babel-cli` resolved that) but now I get this error and don't know why. Any ideas?

I'm using node 4.3.2 because that's the version Lambda is using but I've also tried it with 6.9.4 and I get the same error.

```
$ SLS_DEBUG=* serverless deploy
Serverless: Packaging service...
Serverless: Babel compilation:
tmpBabelDirectory/createResponse.js -> tmpBabelDirectory/createResponse.js
tmpBabelDirectory/handler.js -> tmpBabelDirectory/handler.js

Serverless: Packaging service with compiled files...

  Error --------------------------------------------------

     invalid signature: 0x6064b50

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: invalid signature: 0x6064b50
    at /Users/cmoel/Desktop/sls-babel/node_modules/serverless-babel-plugin/node_modules/unzip2/lib/parse.js:63:13
    at processImmediate [as _immediateCallback] (timers.js:383:17)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.3.2
     Serverless Version: 1.5.0
```

**Comment by DavidWells** [comment]
I was unable to reproduce this error. What version of the framework are you using?

I followed the below steps and this example deployed with no error on sls 1.5.0

What does your ES6 code look like?

## Steps

Install this example
```
sls install --url https://github.com/serverless/examples/tree/master/aws-node-function-compiled-with-babel --name babel
```

Then deploy with `sls deploy`
```
 babel  sls deploy
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Packaging service...
Serverless: Babel compilation:
tmpBabelDirectory/createResponse.js -> tmpBabelDirectory/createResponse.js
tmpBabelDirectory/handler.js -> tmpBabelDirectory/handler.js

Serverless: Packaging service with compiled files...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (5.03 MB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
...............
Serverless: Stack update finished...
Service Information
service: babel
stage: dev
region: us-east-1
api keys:
  None
endpoints:
  None
functions:
  babel-dev-hello: arn:aws:lambda:us-east-1:488110005556:function:babel-dev-hello
```

**Comment by cmoel** [comment]
I'm very confused as to why I was having an issue earlier now... I just followed these steps and everything worked correctly:
```
sls install --url https://github.com/serverless/examples/tree/master/aws-node-function-compiled-with-babel --name babel
cd babel/
npm install
sls deploy
```

Thanks for an awesome framework and for looking into this, sorry for the trouble!

**Comment by cmoel** [comment]
I was just playing with this a bit more to help try to figure out what I was doing wrong. I noticed the issue when I was using node 4.3.2 with npm 2.14.12. but the service deploys successfully using node 6.9.4 with npm 3.10.10.

**Comment by nikunjdnp** [comment]
I am getting the error something like: 
`D:\babel\node_modules\serverless-babel-plugin\index.js:56
        const stdout = result.stdout.toString();
                                     ^

TypeError: Cannot read property 'toString' of null
    at Extract.stream.on (D:\babel\node_modules\serverless-babel-plugin\index.js:56:38)
    at emitNone (events.js:111:20)
    at Extract.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:604:14)
    at endWritable (_stream_writable.js:612:3)
    at Extract.Writable.end (_stream_writable.js:563:5)
    at ReadStream.onend (_stream_readable.js:595:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at ReadStream.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)`

npm version is 5.5.1 and node version is 8.9.1.
