### ISSUE TITLE
Python Runtime is not supported

### ISSUE THREAD

**Issue by sarveshbhatnagar** [serverless/examples#626]
Failed to deploy function (openwhisk-python-simple-dev-greeting) due to error: PUT https://eu-gb.functions.cloud.ibm.com/api/v1/namespaces/_/actions/openwhisk-python-simple-dev-greeting?overwrite=true Returned HTTP 400 (Bad Request) --> "The 'python' runtime is no longer supported. You may read and delete but not update or invoke this action."

**Comment by pgrzesik** [comment]
Closing as PR with fix has been merged
