### ISSUE TITLE
[aws-python-flask-api] Startup code has incorrect requirements.txt

### ISSUE THREAD

**Issue by Noprop** [serverless/examples#649]
Going through the process at [https://app.serverless.com/your_username/apps/new?package=aws-python-flask-api](https://app.serverless.com/your_username/apps/new?package=aws-python-flask-api) does not work as it is missing the Werkzeug dependency in requirements.txt

This is what the requirements.txt file is supposed to look like:

[https://github.com/serverless/examples/blob/4b147426fc7f7499047eadce93c885f955af1347/aws-python-flask-api/requirements.txt](https://github.com/serverless/examples/blob/4b147426fc7f7499047eadce93c885f955af1347/aws-python-flask-api/requirements.txt)

**Comment by pgrzesik** [comment]
Hey @Noprop, thanks a lot for reporting, I've passed it internally and I'll come back as soon as possible
