### ISSUE TITLE
[BUG] Example: aws-python-simple-http-endpoint, /ping endpoint doesn't work

### ISSUE THREAD

**Issue by richardstrnad** [serverless/examples#667]
Hi Team,

Thanks for the great examples! Really help to get started.
But i struggled today a bit with the `aws-python-simple-http-endpoint` example, as the call to the `/ping` endpoint always returned `Healthy Connection`.

Finally i realized that `/ping` seems to be a "default" endpoint? As soon as i changed `path: /ping` to `path: /time` the example worked as expected.

```
→ curl https://8rsniq0o64.execute-api.eu-north-1.amazonaws.com/ping
Healthy Connection
```

```
→ curl https://8rsniq0o64.execute-api.eu-north-1.amazonaws.com/time
{"message": "Hello, the current time is 13:51:40.743825"}
```

Am I missing something? Like a way to disable the `/ping` behaviour? Or should we just change the example to a different path?

**Comment by pgrzesik** [comment]
Hello @richardstrnad - I believe this is an omission in the example as `/ping` is reserved by API Gateway and should be changed to something else e.g. `/time` as you did. We'd be happy to accept a PR with that change to mentioned example :raised_hands:
