### ISSUE TITLE
aws-node-rest-api-with-dynamodb example non string error

### ISSUE THREAD

**Issue by DanielBlackburn** [serverless/examples#70]
I am getting the following issue with the aws-node-rest-api-with-dynamodb example.  Have I missed something in the configuration.  AWS cli seems to configured correctly as other examples deployed OK. 

Serverless Error ---------------------------------------
 
     Trying to populate non string value into a string for
     variable ${env:DYNAMODB_TABLE}. Please make sure the
     value of the property is a string.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.4.0
     Serverless Version: 1.6.1

**Comment by mallize** [comment]
I solved this by exporting an environment variable "DYNAMODB_TABLE" and setting it to my desired table name. You could also hard code it.
