### ISSUE TITLE
aws-node-rest-api-with-dynamodb 502 Bad Gateway

### ISSUE THREAD

**Issue by mallize** [serverless/examples#71]
When I execute any of my resources I get 502 Bad Gateway. 

Here is the exact response when ran from the API Gateway console:

> Execution log for request test-request
Sat Feb 04 04:37:12 UTC 2017 : Starting execution for request: test-invoke-request
Sat Feb 04 04:37:12 UTC 2017 : HTTP Method: GET, Resource Path: /todos
Sat Feb 04 04:37:12 UTC 2017 : Method request path: {}
Sat Feb 04 04:37:12 UTC 2017 : Method request query string: {}
Sat Feb 04 04:37:12 UTC 2017 : Method request headers: {}
Sat Feb 04 04:37:12 UTC 2017 : Method request body before transformations: 
Sat Feb 04 04:37:12 UTC 2017 : Endpoint request URI: https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/arn:aws:lambda:us-east-1xxxxxx:function:serverless-rest-api-with-dynamodb-dev-list/invocations
Sat Feb 04 04:37:12 UTC 2017 : Endpoint request headers: {x-amzn-lambda-integration-tag=test-request, Authorization=****************************************************************************************************************************************************************************************************************************************************************************************************************************************, X-Amz-Date=20170204T043712Z, x-amzn-apigateway-api-id=xxxxxxxxxx, X-Amz-Source-Arn=arn:aws:execute-api:us-east-1:xxxxxxxxx/null/GET/todos, Accept=application/json, User-Agent=AmazonAPIGateway_xxxxxxx, X-Amz-Security-
[----omitted----]
Sat Feb 04 04:37:12 UTC 2017 : Endpoint response body before transformations: {"errorMessage":"Couldn't fetch the todos.","errorType":"Error","stackTrace":["Response.<anonymous> (/var/task/todos/list.js:16:16)","Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:355:18)","Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)","Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)","Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:668:14)","Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)","AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)","/var/task/node_modules/aws-sdk/lib/state_machine.js:26:10","Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)","Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:670:12)"]}
Sat Feb 04 04:37:12 UTC 2017 : Endpoint response headers: {x-amzn-Remapped-Content-Length=0, x-amzn-RequestId=989d821e-ea93-11e6-be3d-6768b0c930a1, Connection=keep-alive, Content-Length=829, X-Amz-Function-Error=Handled, Date=Sat, 04 Feb 2017 04:37:11 GMT, Content-Type=application/json}
Sat Feb 04 04:37:12 UTC 2017 : Execution failed due to configuration error: Malformed Lambda proxy response
Sat Feb 04 04:37:12 UTC 2017 : Method completed with status: 502
> 

I have tried switching to lambda instead of lambda-proxy. This results in a 500.

**Comment by mallize** [comment]
Resolved this. the issue was the env. variable "DYNAMODB_TABLE" for my lambda was pointing at the default table "serverless-rest-api-with-dynamodb-dev", even though i specified a custom table.

**Comment by nikgraf** [comment]
Glad you figured it out 🙌
