### ISSUE TITLE
[aws-node-puppeteer] Example missing information

### ISSUE THREAD

**Issue by fabioselau077** [serverless/examples#748]
The example [aws-node-puppeteer](https://github.com/serverless/examples/tree/v3/aws-node-puppeteer) is missing information, with only the data provided by the example you cannot deploy anything.
For example, it says to create a chrome-script.js file and then import it into handler.js, but the imported function is not used in any movement.

@edit 
lol, I just saw that the repository is 5 years old.
The date on the website does not appear, I thought the example was recent.
https://www.serverless.com/examples/aws-node-puppeteer

There should be a notice on the website that the article is out of date and the packages deprecated.

**Comment by medikoo** [comment]
@fabioselau077 this repository is actively maintained, and examples from it are used in Framework onboarding commands.

Therefore if you feel that the puppeteer example should be updated, we will definitely welcome a PR improvement
