### ISSUE TITLE
Unsupported template aws-node-http-api-typescript

### ISSUE THREAD

**Issue by 0x6C38** [serverless/examples#752]
Serverless version 3.29.0 returns a `Template "aws-node-http-api-typescript" is not supported.` error when trying to use this template. What makes a template supported / unsupported? Can this be fixed? Where is the list of supported templates defined?

**Comment by jpbamberg1993** [comment]
@0x6C38 You just need to specify the URL of the example.
```bash
serverless crate -u https://github.com/serverless/examples/tree/v3/aws-node-http-api-typescript --path new-api
```

**Comment by 0x6C38** [comment]
Thank you
