### ISSUE TITLE
Trying to invoke the hello function locally for template aws-node-http-api  fails using documentation

### ISSUE THREAD

**Issue by mcam10** [serverless/examples#757]
Following the documentation on the template above.. the local invocation of the function fails. The function name is **API** not Hello.

Just need to update the documentation to reflect the correct function name.

**Comment by medikoo** [comment]
@mcam10 PR with a fix to the documentation is welcome!

**Comment by mcam10** [comment]
This will be addressed in this PR 
https://github.com/serverless/examples/pull/765
