### ISSUE TITLE
Contact for uses of serverless

### ISSUE THREAD

**Issue by tomberek** [serverless/examples#97]
README mentions we should contact someone when we create applications derived from serverless examples. Who should we contact?

**Comment by christophgysin** [comment]
Where does it say so?

If you need to contact the serverless folks, there is an email address mentioned in the README.

**Comment by tomberek** [comment]
@christophgysin : at the end of https://github.com/serverless/examples/blob/master/aws-node-github-webhook-listener/README.md

**Comment by DavidWells** [comment]
Hey @tomberek what can I help you with?
